// Sticker Templates - Circle Stickers
export const stickerTemplates = [
  {
    id: 'circle-business-logo',
    name: 'Business Logo Circle',
    description: 'Professional business logo in a clean circle design',
    category: 'business',
    thumbnail: '/assets/images/templates/circle-business-logo.jpg',
    elements: [
      {
        id: 'circle-logo-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 80,
        fill: '#1e3a8a',
        stroke: '#ffffff',
        strokeWidth: 4
      },
      {
        id: 'circle-logo-text',
        type: 'text',
        x: 150,
        y: 150,
        text: 'YOUR LOGO',
        fontSize: 24,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },
  {
    id: 'circle-contact-info',
    name: 'Contact Info Circle',
    description: 'Contact information in a professional circle format',
    category: 'business',
    thumbnail: '/assets/images/templates/circle-contact-info.jpg',
    elements: [
      {
        id: 'circle-contact-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 75,
        fill: '#ffffff',
        stroke: '#1e3a8a',
        strokeWidth: 3
      },
      {
        id: 'circle-contact-name',
        type: 'text',
        x: 150,
        y: 120,
        text: 'YOUR NAME',
        fontSize: 18,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#1e3a8a',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-contact-phone',
        type: 'text',
        x: 150,
        y: 150,
        text: '(555) 123-4567',
        fontSize: 14,
        fontFamily: 'Arial, sans-serif',
        fill: '#374151',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-contact-email',
        type: 'text',
        x: 150,
        y: 180,
        text: 'email@company.com',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        fill: '#6b7280',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 37, y: 37, width: 225, height: 225 }
  },
  {
    id: 'circle-event-badge',
    name: 'Event Badge Circle',
    description: 'Event or conference badge in circle format',
    category: 'event',
    thumbnail: '/assets/images/templates/circle-event-badge.jpg',
    elements: [
      {
        id: 'circle-event-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 85,
        fill: '#dc2626',
        stroke: '#ffffff',
        strokeWidth: 5
      },
      {
        id: 'circle-event-title',
        type: 'text',
        x: 150,
        y: 105,
        text: 'EVENT 2024',
        fontSize: 16,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-event-name',
        type: 'text',
        x: 150,
        y: 150,
        text: 'YOUR NAME',
        fontSize: 20,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-event-company',
        type: 'text',
        x: 150,
        y: 195,
        text: 'COMPANY NAME',
        fontSize: 14,
        fontFamily: 'Arial, sans-serif',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 22, y: 22, width: 255, height: 255 }
  },
  {
    id: 'circle-social-media',
    name: 'Social Media Circle',
    description: 'Social media handle in circle format',
    category: 'social',
    thumbnail: '/assets/images/templates/circle-social-media.jpg',
    elements: [
      {
        id: 'circle-social-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 80,
        fill: '#3b82f6',
        stroke: '#ffffff',
        strokeWidth: 4
      },
      {
        id: 'circle-social-icon',
        type: 'text',
        x: 150,
        y: 120,
        text: '@',
        fontSize: 32,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-social-handle',
        type: 'text',
        x: 150,
        y: 180,
        text: 'YOURHANDLE',
        fontSize: 16,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },
  {
    id: 'circle-warning',
    name: 'Warning Circle',
    description: 'Warning or caution sticker in circle format',
    category: 'safety',
    thumbnail: '/assets/images/templates/circle-warning.jpg',
    elements: [
      {
        id: 'circle-warning-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 85,
        fill: '#fbbf24',
        stroke: '#000000',
        strokeWidth: 4
      },
      {
        id: 'circle-warning-symbol',
        type: 'text',
        x: 150,
        y: 120,
        text: '⚠',
        fontSize: 40,
        fontFamily: 'Arial, sans-serif',
        fill: '#000000',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'circle-warning-text',
        type: 'text',
        x: 150,
        y: 180,
        text: 'WARNING',
        fontSize: 18,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#000000',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 22, y: 22, width: 255, height: 255 }
  },
  {
    id: 'circle-decorative',
    name: 'Decorative Circle',
    description: 'Decorative circle with pattern or design',
    category: 'decorative',
    thumbnail: '/assets/images/templates/circle-decorative.jpg',
    elements: [
      {
        id: 'circle-decorative-bg',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 80,
        fill: '#8b5cf6',
        stroke: '#ffffff',
        strokeWidth: 3
      },
      {
        id: 'circle-decorative-pattern',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 60,
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2
      },
      {
        id: 'circle-decorative-center',
        type: 'circle',
        x: 150,
        y: 150,
        radius: 20,
        fill: '#ffffff'
      },
      {
        id: 'circle-decorative-text',
        type: 'text',
        x: 150,
        y: 150,
        text: 'DESIGN',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#8b5cf6',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },

  // Square Sticker Templates
  {
    id: 'square-business-logo',
    name: 'Business Logo Square',
    description: 'Professional business logo in a clean square design',
    category: 'business',
    thumbnail: '/assets/images/templates/square-business-logo.jpg',
    elements: [
      {
        id: 'square-logo-bg',
        type: 'rect',
        x: 50,
        y: 50,
        width: 200,
        height: 200,
        fill: '#1e3a8a',
        stroke: '#ffffff',
        strokeWidth: 4,
        cornerRadius: 10
      },
      {
        id: 'square-logo-text',
        type: 'text',
        x: 150,
        y: 150,
        text: 'YOUR LOGO',
        fontSize: 24,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },
  {
    id: 'square-contact-info',
    name: 'Contact Info Square',
    description: 'Contact information in a professional square format',
    category: 'business',
    thumbnail: '/assets/images/templates/square-contact-info.jpg',
    elements: [
      {
        id: 'square-contact-bg',
        type: 'rect',
        x: 50,
        y: 50,
        width: 200,
        height: 200,
        fill: '#059669',
        stroke: '#ffffff',
        strokeWidth: 4,
        cornerRadius: 10
      },
      {
        id: 'square-contact-text',
        type: 'text',
        x: 150,
        y: 120,
        text: 'COMPANY NAME',
        fontSize: 18,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-phone-text',
        type: 'text',
        x: 150,
        y: 150,
        text: '(555) 123-4567',
        fontSize: 14,
        fontFamily: 'Arial, sans-serif',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-email-text',
        type: 'text',
        x: 150,
        y: 180,
        text: 'info@company.com',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },
  {
    id: 'square-event-badge',
    name: 'Event Badge Square',
    description: 'Square badge design for events and conferences',
    category: 'event',
    thumbnail: '/assets/images/templates/square-event-badge.jpg',
    elements: [
      {
        id: 'square-event-bg',
        type: 'rect',
        x: 50,
        y: 50,
        width: 200,
        height: 200,
        fill: '#dc2626',
        stroke: '#ffffff',
        strokeWidth: 4,
        cornerRadius: 15
      },
      {
        id: 'square-event-text',
        type: 'text',
        x: 150,
        y: 120,
        text: 'EVENT',
        fontSize: 20,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-event-name',
        type: 'text',
        x: 150,
        y: 150,
        text: 'CONFERENCE 2024',
        fontSize: 16,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-event-date',
        type: 'text',
        x: 150,
        y: 180,
        text: 'JAN 15-17',
        fontSize: 14,
        fontFamily: 'Arial, sans-serif',
        fill: '#ffffff',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  },
  {
    id: 'square-warning-label',
    name: 'Warning Label Square',
    description: 'Square warning or safety label design',
    category: 'safety',
    thumbnail: '/assets/images/templates/square-warning-label.jpg',
    elements: [
      {
        id: 'square-warning-bg',
        type: 'rect',
        x: 50,
        y: 50,
        width: 200,
        height: 200,
        fill: '#f59e0b',
        stroke: '#000000',
        strokeWidth: 3,
        cornerRadius: 5
      },
      {
        id: 'square-warning-icon',
        type: 'text',
        x: 150,
        y: 120,
        text: '⚠️',
        fontSize: 40,
        fontFamily: 'Arial, sans-serif',
        fill: '#000000',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-warning-text',
        type: 'text',
        x: 150,
        y: 170,
        text: 'WARNING',
        fontSize: 18,
        fontFamily: 'Arial, sans-serif',
        fontStyle: 'bold',
        fill: '#000000',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      },
      {
        id: 'square-warning-desc',
        type: 'text',
        x: 150,
        y: 200,
        text: 'HOT SURFACE',
        fontSize: 14,
        fontFamily: 'Arial, sans-serif',
        fill: '#000000',
        align: 'center',
        verticalAlign: 'middle',
        width: 'auto',
        height: 'auto',
        wrap: 'none'
      }
    ],
    canvasSize: { width: 300, height: 300 },
    safeZone: { x: 30, y: 30, width: 240, height: 240 }
  }
]
